POST http://localhost:8080/users/authenticate
Content-Type: application/json

{
  "username": "carlos.montoya.rdgz@gmail.com",
  "password": "sipirili"
}

###

GET http://localhost:8080/checks
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJtaW5vSldUIiwic3ViIjoiY2FybG9zLm1vbnRveWEucmRnekBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNTcxMTg2NDQ3LCJleHAiOjE1NzExODcwNDd9._R13W3_lCGIFE6aM8TvmS-p89KRQ3gIEEpThJI-AC93oMJ4NM9aOnAmakosrVXtoUDR3V_CmycXQkpX2vKJf5g

###

POST http://localhost:8080/checks
Content-Type: application/json

{
  "empleado": "/users/2",
  "fecha": "2020-12-31",
  "hora": "14:20:32",
  "tipoCheck": "SALIDA"
}

###

GET http://localhost:8080/checks/search/findByEmpleadoAndFecha?empleado=/users/1&fecha=16/10/19
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJtaW5vSldUIiwic3ViIjoiY2FybG9zLm1vbnRveWEucmRnekBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNTcxMjAyOTA0LCJleHAiOjE1NzEyMDM1MDR9.fx1EE4-vK1pVBmdWv5wUhg7HI7xxS2ULhhUfxQWUneUVkj8OGDsyRyychp_1ciHHN9LzsvEoBRiAjgNyMxu5bw
###
