POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "javainuse@gmail.com",
  "password": "password"
}

###

GET http://localhost:8080/api/checks
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2VAZ21haWwuY29tIiwiZXhwIjoxNTc0NTg0MjEwLCJpYXQiOjE1NzQ1NjYyMTB9.jjxWlJhYUhSg1E9RlNmSoaw-dIj-nX33tGn-YzyVtkKmnXS10p00qxtTGq0qROtKWQkN6515mto1ZicxZLihyg


###

POST http://localhost:8080/api/checks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2VAZ21haWwuY29tIiwiZXhwIjoxNTc0NTg0MjEwLCJpYXQiOjE1NzQ1NjYyMTB9.jjxWlJhYUhSg1E9RlNmSoaw-dIj-nX33tGn-YzyVtkKmnXS10p00qxtTGq0qROtKWQkN6515mto1ZicxZLihyg

{
  "empleado": "/users/999999",
  "tipoCheck": "SALIDA"
}

###

GET http://localhost:8080/checks/search/findByEmpleadoAndFecha?empleado=/users/1&fecha=16/10/19
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJtaW5vSldUIiwic3ViIjoiY2FybG9zLm1vbnRveWEucmRnekBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNTcyNTUwNDkzLCJleHAiOjE1NzI2MTA0OTN9.osSlTrE1p8aLX0FJDXEQLeo074S-FBeRDDvrAXo5i7HkHpCtBOvpf8W1QyXYvbRgIGe-FC_ufxHyV_gB9xcHmQ

###

GET http://localhost:8080/checks/search/findByFechaGreaterThanEqual?from=11/10/19
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJtaW5vSldUIiwic3ViIjoiY2FybG9zLm1vbnRveWEucmRnekBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNTcxODE2NDUxLCJleHAiOjE1NzE4MTcwNTF9.HoDiR4IX6cUTgRYQRJz2SdjvmgioPl2OBkBJK3RmttTmdW8DCmaWPaHlrBZWfCUiMT73IHnQ68HoC6SyxLoHNg

###
