POST http://localhost:8080/users/authenticate
Content-Type: application/json

{
  "username": "carlos.montoya.rdgz@gmail.com",
  "password": "sipirili"
}

###

GET http://localhost:8080/users/19
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJtaW5vSldUIiwic3ViIjoiY2FybG9zLm1vbnRveWEucmRnekBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNTcwOTM0ODM4LCJleHAiOjE1NzA5MzU0Mzh9.QL8w9JFKLEUlD9iuWAf4MXwEAFvZ8UCLUsPuER95XTQpbQo6i0kmNTXlp1AJmoUhVq6vJFxfT2yhlfMpdVi22w

###

GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJtaW5vSldUIiwic3ViIjoiY2FybG9zLm1vbnRveWEucmRnekBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNTcwOTM0ODM4LCJleHAiOjE1NzA5MzU0Mzh9.QL8w9JFKLEUlD9iuWAf4MXwEAFvZ8UCLUsPuER95XTQpbQo6i0kmNTXlp1AJmoUhVq6vJFxfT2yhlfMpdVi22w

###

POST http://localhost:8080/users/register
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJtaW5vSldUIiwic3ViIjoiY2FybG9zLm1vbnRveWEucmRnekBnbWFpbC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaWF0IjoxNTcwOTM0ODM4LCJleHAiOjE1NzA5MzU0Mzh9.QL8w9JFKLEUlD9iuWAf4MXwEAFvZ8UCLUsPuER95XTQpbQo6i0kmNTXlp1AJmoUhVq6vJFxfT2yhlfMpdVi22w
Content-Type: application/json

{
  "username": "diego.b@outlook.com",
  "password": "pass123",
  "rolNombre": "ROL_USER"
}

###
