POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "carlos.montoya.rdgz@gmail.com",
  "password": "sipirili"
}

###

POST http://localhost:8080/authenticate
Content-Type: application/json

{
  "username": "mario.anzures@outlook.com",
  "password": "noporolo"
}

###

GET http://localhost:8080/api/usuarios?page=0&projection=datos
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjYXJsb3MubW9udG95YS5yZGd6QGdtYWlsLmNvbSIsImV4cCI6MTU3NDc1MDkwMCwiaWF0IjoxNTc0NzMyOTAwfQ.XI6DPe6r8v-2FgLsIMNoomnSSxSTD_aKRuqXMz-AHUmykOeGhUG218BrjB2YSfOBpY6Dy7dmLuD3qvPMIyFkvA
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJtYXJpby5hbnp1cmVzQG91dGxvb2suY29tIiwiZXhwIjoxNTc0NzY1ODYyLCJpYXQiOjE1NzQ3NDc4NjJ9.Z-yVprm27QYcmuJnF-p57Wrqub6iOp8dBc3NPHhqb6QDj3HgFwxP9Ia52Kw8ulzuR2JEY99zu0Zx5JtqEM16og

###

GET http://localhost:8080/api/usuarios/60
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2VAZ21haWwuY29tIiwiZXhwIjoxNTc0NTg0MjEwLCJpYXQiOjE1NzQ1NjYyMTB9.jjxWlJhYUhSg1E9RlNmSoaw-dIj-nX33tGn-YzyVtkKmnXS10p00qxtTGq0qROtKWQkN6515mto1ZicxZLihyg

###

GET http://localhost:8080/api/usuarios/60?projection=datos
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2VAZ21haWwuY29tIiwiZXhwIjoxNTc0NTg0MjEwLCJpYXQiOjE1NzQ1NjYyMTB9.jjxWlJhYUhSg1E9RlNmSoaw-dIj-nX33tGn-YzyVtkKmnXS10p00qxtTGq0qROtKWQkN6515mto1ZicxZLihyg

###

GET http://localhost:8080/api/usuarios/search/findByUsername?username=carlos.montoya.rdgz@gmail.com&projection=datos
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqYXZhaW51c2VAZ21haWwuY29tIiwiZXhwIjoxNTc0NTg0MjEwLCJpYXQiOjE1NzQ1NjYyMTB9.jjxWlJhYUhSg1E9RlNmSoaw-dIj-nX33tGn-YzyVtkKmnXS10p00qxtTGq0qROtKWQkN6515mto1ZicxZLihyg

###

POST http://localhost:8080/api/usuarios/registro
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjYXJsb3MubW9udG95YS5yZGd6QGdtYWlsLmNvbSIsImV4cCI6MTU3NDYwODQwNSwiaWF0IjoxNTc0NTkwNDA1fQ.azfUOMBti-bF--hqCAUvsotKAm0la1cUXdGXB1AwbKWBrWSZ2YlgB_g8G9-fc1s5ob-kh4iXvqhZ7ZhhZkk9Bw
Content-Type: application/json

{
  "username": "mario.anzures@outlook.com",
  "password": "noporolo",
  "rolNombre": "EMPLEADO"
}

###
